### ISSUE TITLE
Syntax for tags

### ISSUE THREAD

**Issue by joesiltberg** [dotse/tls-fed-auth#4]
We should specify syntax and comparison rules for tags.

I suggest a simple syntax consisting of only the letters a-z, A-Z and digits. If hyphens are allowed they should not be allowed as the first character (since they could be specified on command line).

Case insensitive comparisons I suppose?

**Comment by joesiltberg** [comment]
It would be nice to have a concise way of specifying the list of tags on the command line, for instance comma separated:

```
sync --entity example.org --server-tags scim,prod
````
This works with the suggested syntax above, but not if the tags can include comma.

**Comment by jschlyter** [comment]
Tags are now "^[a-z0-9]{1,64}$"
